[package]
name = "pluribus-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "pluribus"
path = "src/main.rs"

[dependencies]
jsonschema.workspace = true
futures-util.workspace = true
tokio.workspace = true
clap.workspace = true
flate2 = { workspace = true }
tar = { workspace = true }
reqwest.workspace = true
rustix.workspace = true
url.workspace = true
pluribus-cognition = { path = "../pluribus-cognition" }
pluribus-core = { path = "../pluribus-core" }
pluribus-host-http = { path = "../pluribus-host-http" }
pluribus-host-stream = { path = "../pluribus-host-stream" }
pluribus-log = { path = "../pluribus-log" }
pluribus-paths = { path = "../pluribus-paths" }
pluribus-plugin-package = { path = "../pluribus-plugin-package" }
pluribus-runtime-wasm = { path = "../pluribus-runtime-wasm" }
pluribus-store-fs = { path = "../pluribus-store-fs" }
pluribus-store-sqlite = { path = "../pluribus-store-sqlite" }
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tracing.workspace = true

[build-dependencies]
serde_json.workspace = true

[dev-dependencies]
async-trait.workspace = true
rcgen = { workspace = true }
tempfile.workspace = true
tokio-rustls = { workspace = true, features = ["ring"] }

[lints]
workspace = true
