[package]
name = "pluribus-runtime-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
http.workspace = true
http-body-util.workspace = true
http-body.workspace = true
bytes.workspace = true
futures-util.workspace = true
wasmtime-wasi-http.workspace = true
getrandom.workspace = true
pluribus-host-http = { path = "../pluribus-host-http" }
tokio.workspace = true
pluribus-core = { path = "../pluribus-core" }
pluribus-plugin-bindings = { path = "../pluribus-plugin-bindings" }
pluribus-plugin-package = { path = "../pluribus-plugin-package" }
serde.workspace = true
serde_json.workspace = true
wasmtime.workspace = true

[dev-dependencies]
async-trait.workspace = true
pluribus-store-sqlite = { path = "../pluribus-store-sqlite" }
pluribus-host-stream = { path = "../pluribus-host-stream" }
rustix.workspace = true
reqwest.workspace = true
ring = "0.17"
tempfile.workspace = true
wit-component.workspace = true
wit-parser.workspace = true
jsonschema.workspace = true

[lints]
workspace = true
