[package]
name = "pluribus-plugin-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
wasmtime-wasi-http.workspace = true
wasmtime.workspace = true

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = "warn"
pedantic = "warn"
