[package]
name = "pluribus-host-http"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
tokio-util.workspace = true
futures-util.workspace = true
tokio.workspace = true
async-trait.workspace = true
pluribus-core = { path = "../pluribus-core" }
reqwest.workspace = true
serde_json.workspace = true

[lints]
workspace = true
